var appliancesCarbonCoop = {
    "Laundry": {
        "Clothes washing - hot feed": {
            "Norm demand": 1.1,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 55,
            "Reference quantity": 3,
            "Electric fraction": 0.55,
            "DHW fraction": 0.45,
            "GAS fraction": 0
        },
        "Clothes washing - cold feed": {
            "Norm demand": 1.1,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 55,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction":0,
        },
        "Clothes Drying - electric dryer": {
            "Norm demand": 4,
            "Units": "kWh per use",
            "Utilisation factor": 0.88,
            "Frequency": 57,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
    },
    "Food storage": {
        "Refrigerator": {
            "Norm demand": 0.65,
            "Units": "kWh per day",
            "Utilisation factor": 1,
            "Frequency": 365,
            "Reference quantity": 1,
            "Electric fraction": 1, 
            "DHW fraction": 0,
            "GAS fraction": 0
        },
        "Upright Freezer": {
            "Norm demand": 0.89,
            "Units": "kWh per day",
            "Utilisation factor": 1,
            "Frequency": 365,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "Chest Freezer": {
            "Norm demand": 1,
            "Units": "kWh per day",
            "Utilisation factor": 1,
            "Frequency": 365,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "Fridge/Freezer": {
            "Norm demand": 1.16,
            "Units": "kWh per day",
            "Utilisation factor": 1,
            "Frequency": 365,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
    },
    "Cooking": {
        "gas hob, gas oven": {
            "Norm demand": 0.25,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 500,
            "Reference quantity": 3, 
            "Electric fraction": 0,
            "DHW fraction": 1,
            "GAS fraction": 0,
        },
        "gas hob, electric oven": {
            "Norm demand": 0.25,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 500,
            "Reference quantity": 3, 
            "Electric fraction": 0.5,
            "DHW fraction": 0,
            "GAS fraction": 0.5,
        },
        "electric hob, electric oven (standard)": {
            "Norm demand": 0.22,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 500,
            "Reference quantity": 3, 
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "electric hob, electric oven (induction)": {
            "Norm demand": 0.2,
            "Units": "kWh per use",
            "Utilisation factor":1 ,
            "Frequency": 500,
            "Reference quantity": 3, 
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction":0 
        },
        "range/aga - gas/oil": {
            "Norm demand": 425,
            "Units": "KWh per week",
            "Utilisation factor":1 ,
            "Frequency": 52,
            "Reference quantity": 1,
            "Electric fraction": 0,
            "DHW fraction": 1,
            "GAS fraction": 0,
        },
        "range/aga - electric ": {
            "Norm demand": 220,
            "Units": "KWh per week",
            "Utilisation factor": 1,
            "Frequency": 52,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "microwave": {
            "Norm demand": 14,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        }
    },
    "Other kitchen / cleaning": {
        "electric kettle": {
            "Norm demand": 20,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0
        },
        "Dishwasher - hot feed": {
            "Norm demand": 1.5,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 65,
            "Reference quantity": 3,
            "Electric fraction": 0.5,
            "DHW fraction": 0.5, 
            "GAS fraction": 0,
        },
        "Dishwasher - cold feed": {
            "Norm demand": 1.5,
            "Units": "kWh per use",
            "Utilisation factor": 1,
            "Frequency": 65,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
    },
    "TV": {
        "TV - CRT": {
            "Norm demand": 118,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "TV - LCD/LED": {
            "Norm demand": 199,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "TV - Plasma": {
            "Norm demand": 658,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
    },
    "Computing": {
        "Desktop": {
            "Norm demand": 166,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "Laptop": {
            "Norm demand": 29,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "Computer Peripherals": {
            "Norm demand": 50,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
    },
    "Misc": {
        "Small Consumer Electronics ": {
            "Norm demand": 0.080,
            "Units": "kW",
            "Utilisation factor": 1,
            "Frequency": 0.55,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "Other Small Appliances": {
            "Norm demand": 50,
            "Units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 3,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        },
        "Standby": {
            "Norm demand": 343,
            "units": "kWh",
            "Utilisation factor": 1,
            "Frequency": 1,
            "Reference quantity": 1,
            "Electric fraction": 1,
            "DHW fraction": 0,
            "GAS fraction": 0,
        }
    }
};
