var standard_library = {
    elements: {
        "CV1": {
            name: "Uninsulated cavity brick",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 1.30,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "CV2": {
            name: "Uninsulated cavity lightweight block",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.96,
            kvalue: 140,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "CV3": {
            name: "Uninsulated cavity wall",
            source: "Historic Scotland in situ measurements p38",
            location: '',
            uvalue: 1.2,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "CV4": {
            name: "Insulated cavity wall",
            source: "Historic Scotland in situ measurements p38",
            location: '',
            uvalue: 0.3,
            kvalue: 190,
            tags: ["Wall"],
            criteria: ["CV1", "CV2", "CV3", "CV5"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "CV5": {
            name: "Cavity walls involving brick and block with external render (for 1919-1975)",
            source: "Energy Saving Trust (EST) 2004, table 2, via Historic Scotland p38",
            location: '',
            uvalue: 1.7,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "CV6": {
            name: "Brick/block cavity walls with insulation (for 2003-present)",
            source: "Energy Saving Trust (EST) 2004, table 2, via Historic Scotland p38",
            location: '',
            uvalue: 0.3,
            kvalue: 190,
            tags: ["Wall"],
            criteria: ["CV1", "CV2", "CV3", "CV5"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "CV7": {
            name: "Brick/brick cavity wall with 105mm brick, 50mm airspace, 105mm brick and 13mm dense plaster",
            source: "CIBSE Guide (Anderson, 2006a, tables 3.49 and 3.50, via Historic Scotland p38",
            location: '',
            uvalue: 1.44,
            kvalue: 70,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "SLD1": {
            name: "Uninsulated 600mm stone wall finished with 'plaster on laths'",
            source: "Historic Scotland in situ measurements p38",
            location: '',
            uvalue: 1.1,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "SLD2": {
            name: "Uninsulated 600mm stone wall finished with 'plaster on the hard'",
            source: "Historic Scotland in situ measurements p38",
            location: '',
            uvalue: 1.6,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "SLD3": {
            name: "Uninsulated 600mm stone wall finished with plasterboard",
            source: "Historic Scotland in situ measurements p38",
            location: '',
            uvalue: 0.9,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "SLD4": {
            name: "Traditional sandstone or granite dwelling with solid walls: stone thickness typically 600mm with internal lath and plaster finish (for the pre-1919 period)",
            source: "Energy Saving Trust (EST) 2004, table 2, via Historic Scotland p38",
            location: '',
            uvalue: 1.7,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "SLD5": {
            name: "600mm stonewall with a 50mm airspace and finished with 25mm dense plaster on laths",
            source: "CIBSE Guide (Anderson, 2006a, tables 3.49 and 3.50, via Historic Scotland p38",
            location: '',
            uvalue: 1.38,
            kvalue: 110,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "SLD6": {
            name: "600mm stone wall + 200mm hemp lime",
            source: "Center for Alternative Technology",
            location: '',
            uvalue: 0.58,
            kvalue: 190,
            tags: ["Wall"],
            criteria: ["SLD1", "SLD2", "SLD3"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "TBRF1": {
            name: "Cavity of timber frame wall with 50mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.45,
            kvalue: 18,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "TBRF2": {
            name: "Cavity of timber frame wall with 100mm insulation (2002 UK)",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.35,
            kvalue: 18,
            tags: ["Wall"],
            criteria: ["TBRF1"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "TBRF3": {
            name: "Superinsulated timber frame wall with 250mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.14,
            kvalue: 18,
            tags: ["Wall"],
            criteria: ["TBRF1", "TBRF2"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "BRK1": {
            name: "Solid brick 225mm",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 2.20,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "BRK2": {
            name: "220mm solid brick wall with 13mm dense plaster",
            source: "CIBSE Guide (Anderson, 2006a, tables 3.49 and 3.50, via Historic Scotland p38",
            location: '',
            uvalue: 2.09,
            kvalue: 190,
            tags: ["Wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "BRK3": {
            name: "220mm solid brick wall with 50mm airspace/battens and 12.5mm plasterboard",
            source: "CIBSE Guide (Anderson, 2006a, tables 3.49 and 3.50, via Historic Scotland p38",
            location: '',
            uvalue: 1.41,
            kvalue: 150,
            tags: ["Wall"],
            criteria: ["BRK1", "BRK2"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "RF1": {
            name: "Uninsulated loft",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 2.0,
            kvalue: 9,
            tags: ["Roof"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "RF2": {
            name: "Loft with 100mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.3,
            kvalue: 9,
            tags: ["Roof"],
            criteria: ["RF1"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "RF3": {
            name: "Room in the roof 200mm (2002 UK)",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.2,
            kvalue: 9,
            tags: ["Roof"],
            criteria: ["RF1", "RF2"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "RF4": {
            name: "Loft with 250mm insulation (2002 UK)",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.16,
            kvalue: 9,
            tags: ["Roof"],
            criteria: ["RF1", "RF2", "RF3"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "RF5": {
            name: "Superinsulated loft with 300mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0.12,
            kvalue: 9,
            tags: ["Roof"],
            criteria: ["RF1", "RF2", "RF3", "RF4"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "FLR1": {
            name: "Timber floor uninsulated",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0,
            kvalue: 20,
            tags: ["Floor"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "FLR2": {
            name: "Timber floor with 150mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0,
            kvalue: 20,
            tags: ["Floor"],
            criteria: ["FLR1"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "FLR3": {
            name: "Timber floor superinsulated 250mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0,
            kvalue: 20,
            tags: ["Floor"],
            criteria: ["FLR1", "FLR2"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "FLR4": {
            name: "Solid floor uninsulated (average house)",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0,
            kvalue: 110,
            tags: ["Floor"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "FLR5": {
            name: "Solid floor with 100mm insulation (2002 UK)",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0,
            kvalue: 110,
            tags: ["Floor"],
            criteria: ["FLR4"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "FLR6": {
            name: "Solid floor superinsulated 200mm insulation",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 0,
            kvalue: 110,
            tags: ["Floor"],
            criteria: ["FLR4", "FLR5"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "WND1": {
            name: "Single glazed",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 4.80,
            g: 0.76,
            gL: 0.8,
            ff: 0.7,
            kvalue: 0,
            tags: ["Window"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "WND2": {
            name: "Double-low-E 12mm airspace (2002 UK)",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 2.00,
            g: 0.76,
            gL: 0.8,
            ff: 0.7,
            kvalue: 0,
            tags: ["Window"],
            criteria: ["WND1"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "WND3": {
            name: "Double-low-E Argon fill 16mm airspace",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 1.70,
            g: 0.76,
            gL: 0.8,
            ff: 0.7,
            kvalue: 0,
            tags: ["Window"],
            criteria: ["WND1", "WND2"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "WND4": {
            name: "Triple-low-E Argon fill or double super low-E",
            source: "The Whole House Book p180",
            location: '',
            uvalue: 1.30,
            g: 0.76,
            gL: 0.8,
            ff: 0.7,
            kvalue: 0,
            tags: ["Window"],
            criteria: ["WND1", "WND2", "WND3"],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "PW1": {
            name: "Solid (including structurally insulated panel)",
            source: "SAP2012, table 3.6, p.20",
            location: '',
            uvalue: 0,
            kvalue: 140,
            tags: ["Party_wall"],
            criteria: [],
            description: '--',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "PW2": {
            name: "Unfilled cavity with no effective edge sealing)",
            source: "SAP2012, table 3.6, p.20",
            location: '',
            uvalue: 0.5,
            kvalue: 140,
            tags: ["Party_wall"],
            criteria: [],
            description: 'Unfilled cavity with no effective edge sealing))',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "PW3": {
            name: "Unfilled cavity with effective sealing around all exposed edges and in line with insulation layers in abutting elements",
            source: "SAP2012, table 3.6, p.20",
            location: '',
            uvalue: 0.2,
            kvalue: 140,
            tags: ["Party_wall"],
            criteria: [],
            description: 'Unfilled cavity with effective sealing around all exposed edges and in line with insulation layers in abutting elements',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "PW4": {
            name: "Fully filled cavity with effective sealing at all exposed edges and in line with insulation layers in abutting elements",
            source: "SAP2012, table 3.6, p.20",
            location: '',
            uvalue: 0,
            kvalue: 140,
            tags: ["Party_wall"],
            criteria: [],
            description: 'Fully filled cavity with effective sealing at all exposed edges and in line with insulation layers in abutting elements',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "DR1": {
            name: "Timber door",
            source: "GEM",
            location: '',
            uvalue: 2.8,
            kvalue: 1,
            g: 0.76,
            gL: 0.8,
            ff: 0.4,
            tags: ["Door"],
            criteria: [],
            description: 'Timber door top light',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        },
        "RL1": {
            name: "12mm Velux",
            source: "GEM",
            location: '',
            uvalue: 3.4,
            kvalue: 1,
            g: 0.76,
            gL: 0.8,
            ff: 0.7,
            tags: ["Roof_light"],
            criteria: [],
            description: '12mm Velux',
            performance: '--',
            benefits: '--',
            cost: 0,
            who_by: '--',
            disruption: '--',
            associated_work: '--',
            key_risks: '--',
            notes: '--',
            maintenance: '--'
        }
    },
    systems: {
        'electric': {name: "Standard Electric", efficiency: 1.0, winter: 1.0, summer: 1.0, fuel: 'electric', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'gasboiler': {name: "Standard Gas boiler", efficiency: 0.90, winter: 0.90, summer: 0.80, fuel: 'gas', fans_and_pumps: 45, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'oilboiler': {name: "Oil boiler", efficiency: 0.85, winter: 0.85, summer: 0.85, fuel: 'oil', fans_and_pumps: 100, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'heatpump': {name: "Heatpump", efficiency: 3.0, winter: 3.0, summer: 3.0, fuel: 'electric', fans_and_pumps: 45, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'woodbatch': {name: "Wood batch boiler", efficiency: 0.92, winter: 0.92, summer: 0.92, fuel: 'wood', fans_and_pumps: 45, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'woodpellet': {name: "Wood pellet boiler", efficiency: 0.92, winter: 0.92, summer: 0.92, fuel: 'wood', fans_and_pumps: 45, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'woodstove': {name: "Wood stove", efficiency: 0.87, winter: 0.87, summer: 0.87, fuel: 'wood', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'openwoodfire': {name: "Open wood fire", efficiency: 0.25, winter: 0.25, summer: 0.25, fuel: 'wood', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'electricheater': {name: "Electric room heater", efficiency: 1.0, winter: 1.0, summer: 1.0, fuel: 'electric', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'electricimmersion': {name: "Electric immersion heater", efficiency: 1.0, winter: 1.0, summer: 1.0, fuel: 'electric', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'electric-high': {name: "High rate electric", efficiency: 1.0, winter: 1.0, summer: 1.0, fuel: 'electric-high', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'},
        'electric-low': {name: "Low rate electric", efficiency: 1.0, winter: 1.0, summer: 1.0, fuel: 'electric-low', fans_and_pumps: 0, combi_keep_hot: 0, description: '--', performance: '--', benefits: '--', cost: 0, who_by: '--', disruption: '--', associated_work: '--', key_risks: '--', notes: '--', maintenance: '--'}
    },
    elements_measures: {
        "E-L01": {
            tags: ["Roof", "Loft"],
            name: "Uninsulated loft. ",
            location: "XXX (e.g. main house roof)",
            source: "rdSAP reference",
            uvalue: "3",
            kvalue: 9,
            g: null,
            gL: null,
            ff: null,
            description: "Uninsulated loft space. ",
            performance: 3,
            benefits: "n/a ",
            cost: "n/a",
            who_by: "n/a",
            disruption: "n/a ",
            associated_work: "n/a",
            key_risks: "n/a",
            notes: "n/a",
            maintenance: "n/a"
        },
        "M-L01": {
            tags: ["Roof", "Loft"],
            name: "Loft Insulation (400mm)",
            location: "XXX (e.g. main house roof)",
            source: "Carbon Coop Specification",
            uvalue: "0.1",
            kvalue: 9,
            g: null,
            gL: null,
            ff: null,
            description: "Loft insulation increased to 400mm depth and topped with highly vapour permeable breather membrane to reduce thermal bypass. Vapour-check and air-tightness membrane can also be fitted above ceiling, below insulation, if existing insulation can be moved and ceiling can be accessed. Various materials possible e.g. - recycled formaldehyde free glass wool, recycled plastic bottles, recycled cellulose. ",
            performance: 0.1,
            benefits: "Fuel Bills + Carbon Emissions + Comfort ",
            cost: "£15/sq m",
            who_by: "DIY/ General Contractor",
            disruption: "MINIMAL",
            associated_work: "Loft Hatch, Loft Storage, Roof Insulation, (Internal/Cavity/External Wall Insulation), air-tightness works",
            key_risks: "CONDENSATION: Any cold loft space needs to be ventilated to limit risk of condensation. This may require new ventilation tiles or grills, and the removal of any existing boarding to the rafters. Less critical if existing roofing membrane is fully vapour permeable. COLD BRIDGES: Should be detailed so no gap between loft insulation and any adjacent roof/ wall insulation.",
            notes: "n/a",
            maintenance: "Little maintenace required - though should ensure insulation is not compressed by storing things on it, as this will reduce its effectivemness. "
        },
        "E-W01": {
            tags: ["Wall"],
            name: "Solid brick wall. ",
            location: "XXX (e.g. rear elevation)",
            source: "Carbon Coop Specification (based on on site monitoring)",
            EWI: false,
            uvalue: "1.8",
            kvalue: 190,
            g: null,
            gL: null,
            ff: null,
            description: "Uninsulated solid brick wall (225-240mm thick). ",
            performance: 1.8,
            benefits: "n/a",
            cost: "n/a",
            who_by: "n/a",
            disruption: "n/a",
            associated_work: "n/a",
            key_risks: "n/a",
            notes: "n/a",
            maintenance: "n/a"
        },
        "M-W01": {
            tags: ["Wall"],
            name: "External Wall Insulation (160-200mm)",
            location: "XXX (e.g. rear elevation)",
            source: "Carbon Coop Specification ",
            EWI: true,
            uvalue: "0.2",
            kvalue: 190,
            g: null,
            gL: null,
            ff: null,
            description: "160-200mmmm thick vapour permeable (hygroscopic) woodfibre external wall insulation system (EWI) with render finish. To include insulation to all window and door reveals and thresholds, treatment of roof eaves and verges junctions, taking insulation to at least 200mm below the level of the internal floor (so thermal bridge is reduced). It will also require adjustments of external drainage pipework, and removal/refixing of sundry items (satellite dishes, telephone connections, alarm boxes, boiler flues, bird boxes, gates and fences etc). Alternative finishes - tile hanging, timber cladding, rainscreen etc - may be possible, but will probably increase costs. ",
            performance: 0.2,
            benefits: "Comfort + Carbon Emissions + Fuel Bills",
            cost: "£150/sq m",
            who_by: "Specialist Installer Only",
            disruption: "HIGH",
            associated_work: "windows and doors, roofline works and drainage etc and loft/roof insulation, floor perimeter insulation. ",
            key_risks: "WATER INGRESS AND THERMAL BRIDGING: It is VERY important to pay attention to  all junctions in EWI - so that water cannot get behind the insulation, causing damage and reducing its effectiveness, and so that thermal bridges in the wall are minimised. Junctions with the roof, windows and doors and the floor need careful attention. Gaps in the insulation reduce its effectiveness and create risks to the building structure. You should consider carrying out works to these areas at the same time, for example by re-roofing (or extending the roof), or replacing windows and doors so they can be moved into the insulation layer. SCAffOLD: There will be a requirement for scaffolding, which may need permission from neighbours. CURRENT CONDITION: The current condition of the wall may affect the specification, and repairs may be required before EWI can be applied. ",
            notes: "n/a",
            maintenance: "Need to ensure render and junctions kept in good state of repair to prevent water ingress. Render may need to be patch repaired after 20-30 years, dependent on detailed specification. "
        },
        "E-FL01": {
            tags: ["Floor"],
            name: "Uninsulated suspended timber floor. ",
            location: "XXX (e.g. main house floor)",
            source: "? ",
            uvalue: "This is trickey - as floor U-value also dependent on exposed perimter, void depth etc. Needs thought/discussion.At the moment we work out 'by hand'/ in a separate spreadsheet outside the tool). ",
            kvalue: 9,
            g: null,
            gL: null,
            ff: null,
            description: "Uninsulated suspended timber floor. ",
            performance: null,
            benefits: "",
            cost: "",
            who_by: "",
            disruption: "",
            associated_work: "",
            key_risks: "",
            notes: "n/a",
            maintenance: ""
        },
        "M-FL01": {
            tags: ["Floor"],
            name: "Insulated suspended timber floor. ",
            location: "XXX (e.g. main house floor)",
            source: "?",
            uvalue: "This is trickey - as floor U-value also dependent on exposed perimter, void depth etc. Needs thought/discussion.At the moment we work out 'by hand'/ in a separate spreadsheet outside the tool). ",
            kvalue: 9,
            g: null,
            gL: null,
            ff: null,
            description: "Approx 200mm fibre insulation between/under floor joists. An air-tightness and vapour-check layer should be created at floorboard level (warm side of insulation) with membrane or by sealing between the boards with a proprietary system if this is not possible. If over a cellar, a boarded ceiling can be provided below the floor - this should be vapour permeable, and will increase costs. If void below is small, will require floor to be lifted and re-laid. ",
            performance: 0.2,
            benefits: "Comfort + Carbon Emissions + Fuel Bills",
            cost: "£80/sqm",
            who_by: "General Contractor/DIY",
            disruption: "MEDIUM/HIGH",
            associated_work: "ventilation, internal wall insulation, air-tightness works",
            key_risks: "ROT AND CONDENSATION: Insulating will change the conditions of the sub-floor space, which may increase the risk of damp and rot. The existing condition of the sub-floor and floor joists should be carefully inspected, and it should be ensured that an adequate amount of ventilation is provided to the sub-floor - by un-blocking air-bricks or introducing new ones if needed. Using woodfibre or plant fibre insulation should ensure good hygroscopic performance, but is not a solution where constant damp and moisture is present.If there is an existing damp problem, this should be resolved before the floor is insulated. (Creating an insulated a solid floor may be an alternative solution, especially for smaller voids). ",
            notes: "n/a",
            maintenance: "Should require minimal maintenance. Void should be checked occasionally for signs of damp and moisture. "
        },
        "E-GD01": {
            tags: ["Window"],
            name: "Single glazed timber window. ",
            location: "XXX (Window Ref - W01, W02 etc)",
            source: "rdSAP",
            uvalue: "4.8",
            kvalue: 0,
            g: 0.76,
            gL: 0.8,
            ff: 0.7,
            description: "Single glazed timber-frame window. ",
            performance: 4.8,
            benefits: "n/a",
            cost: "n/a",
            who_by: "n/a",
            disruption: "n/a",
            associated_work: "n/a",
            key_risks: "n/a",
            notes: "n/a",
            maintenance: "n/a"
        },
        "M-GD01": {
            tags: ["Window"],
            name: "Triple glazed timber window",
            location: "XXX (Window Ref - W01, W02 etc)",
            source: "Green Building Store",
            uvalue: "0.8",
            kvalue: 0,
            g: 0.56,
            gL: 0.65,
            ff: 0.7,
            description: "Triple-glazed low-e argon filled windows with warm edge spacers. Fitted in order to be air-tight and with minimal thermal bridging.",
            performance: 0.8,
            benefits: "Comfort + Carbon Emissions + Fuel Bills",
            cost: "£550/sq m",
            who_by: "General Contractor/ Joiner",
            disruption: "HIGH",
            associated_work: "ventilation, EWI, IWI, draught-proofing.  ",
            key_risks: "COLD BRIDGING AND AIR-TIGHTNESS: Risk that windows are fitted poorly, with thermal bridinging and draughts at junction with wall - leading to increased risk of condensation and mold growth on cills and reveals. Minitgate by ensuring window reveals insulated where possible, and window fitted with high level of air-tightness, using appropriate tapes and seals. ",
            notes: "n/a",
            maintenance: "Windows should be jkept clean, inside and out. Hinges and mechanisms should be maintained regularly with appropriate lubricant. May require re-painting on regular basis - likely to be every 5-10 years for factory-applied finishes. "
        },
        "E-GD02": {
            tags: ["Door"],
            name: "Solid Timber Door",
            location: "XXX (Door Ref - D01, D02 etc)",
            source: "rdSAP",
            uvalue: "3",
            kvalue: 0,
            g: null,
            gL: null,
            ff: null,
            description: "Solid timber door",
            performance: 3,
            benefits: "n/a",
            cost: "n/a",
            who_by: "n/a",
            disruption: "n/a",
            associated_work: "n/a",
            key_risks: "n/a",
            notes: "n/a",
            maintenance: "n/a"
        },
        "M-GD02": {
            tags: ["Door"],
            name: "Insulated Timber Door",
            location: "XXX (Door Ref - D01, D02 etc)",
            source: "",
            uvalue: "1",
            kvalue: 0,
            g: null,
            gL: null,
            ff: null,
            description: "Insulated doorset. Fitted to minimise thermal bridges and maintain air-tightness. ",
            performance: 1,
            benefits: "Comfort + Carbon Emissions + Fuel Bills",
            cost: "£1000/unit",
            who_by: "General Contractor/ Joiner",
            disruption: "HIGH",
            associated_work: "ventilation, EWI, IWI, draught-proofing.  ",
            key_risks: "COLD BRIDGING AND AIR-TIGHTNESS: Risk that doors are fitted poorly, with thermal bridinging and draughts at junction with wall - leading to increased risk of condensation and mold growth on cills and reveals. Minitgate by ensuring window reveals insulated where possible, and window fitted with high level of air-tightness, using appropriate tapes and seals. ",
            notes: "n/a",
            maintenance: "Doors should be kept clean, inside and out. Hinges and mechanisms should be maintained regularly with appropriate lubricant. May require re-painting on regular basis - likely to be every 5-10 years for factory-applied finishes. "
        }
    },
    draught_proofing_measures: {
        "DP_TEST": {
            name: "Basic Draughtproffoing Measures - TEST ",
            "q50": 10,
            description: "DP_TEST",
            performance: 3,
            benefits: "DP_TEST",
            cost: "DP_TEST",
            who_by: "DP_TEST",
            disruption: "DP_TEST",
            associated_work: "DP_TEST",
            key_risks: "DP_TEST",
            notes: "DP_TEST",
            maintenance: "DP_TEST"
        }
    },
    ventilation_systems_measures: {
        VS_test: {
            name: "Ventilation Measure - TEST ",
            "ventilation_type": 'IE',
            "system_air_change_rate": 50,
            "balanced_heat_recovery_efficiency": 0.8,
            description: "VS_test",
            performance: 3,
            benefits: "VS_test",
            cost: "VS_test",
            who_by: "VS_test",
            disruption: "VS_test",
            associated_work: "VS_test",
            key_risks: "VS_test",
            notes: "VS_test",
            maintenance: "VS_test"
        }
    },
    extract_ventilation_points: {
        EVP_test: {
            name: "Extract Ventilation Point - TEST ",
            location: "--",
            type: 'Intermittent fan',
            ventilation_rate: 10,
            description: "EVP_test",
            performance: 3,
            benefits: "EVP_test",
            cost: "EVP_test",
            who_by: "EVP_test",
            disruption: "EVP_test",
            associated_work: "EVP_test",
            key_risks: "EVP_test",
            notes: "EVP_test",
            maintenance: "EVP_test"
        }
    },
    /*extract_ventilation_points_measures: {
     EV_test: {
     name: "Extract Ventilation Point Measure - TEST ",
     number_of_intermittentfans_to_add: 1,
     description: "EV_test",
     performance: 3,
     benefits: "EV_test",
     cost: "EV_test",
     who_by: "EV_test",
     disruption: "EV_test",
     associated_work: "EV_test",
     key_risks: "EV_test",
     notes: "EV_test",
     maintenance: "EV_test"
     }
     },*/
    intentional_vents_and_flues: {
        IVF_01: {
            name: 'Standard chimney',
            source: 'SAP',
            type: 'Chimney',
            ventilation_rate: 40
        },
        IVF_02: {
            name: 'Standard open flue',
            source: 'SAP',
            type: 'Open flue',
            ventilation_rate: 20
        },
        IVF_03: {
            name: 'Standard flueless gas fire',
            source: 'SAP',
            type: 'Flueless gas fire',
            ventilation_rate: 40
        }
    },
    intentional_vents_and_flues_measures: {
        IV_test: {
            name: "Intentioanl vents... - TEST ",
            ventilation_rate: 5,
            source: 'IV_test',
            description: "IV_test",
            performance: 3,
            benefits: "IV_test",
            cost: "IV_test",
            who_by: "IV_test",
            disruption: "IV_test",
            associated_work: "IV_test",
            key_risks: "IV_test",
            notes: "IV_test",
            maintenance: "IV_test"
        }
    },
    water_usage: {
        HW_01: {
            name: "Standard Water Use",
            source: '',
            description: "",
            performance: '',
            benefits: "",
            cost: "",
            who_by: "",
            disruption: "",
            associated_work: "",
            key_risks: "",
            notes: "",
            maintenance: ""
        },
        HW_02: {
            name: "Spray Taps",
            source: '',
            description: "Low flow taps fitted to reduce hot water consumption. Kitchen & utility room taps could allow manual over-ride of low-flow when needed for filling sinks/ buckets etc.",
            performance: '4 litres/minute',
            benefits: "Fuel Bills, Carbon Emissions",
            cost: "£150/unit",
            who_by: "Plumber/ DIY",
            disruption: "Minimal",
            associated_work: "",
            key_risks: "n/a",
            notes: "",
            maintenance: ""
        },
        HW_03: {
            name: "Flow Restrictor for Taps",
            source: '',
            description: "Retrofit flow-restrictors to existing hot water taps to reduce hot water cons",
            performance: '4 litres/minute',
            benefits: "Fuel Bills, Carbon Emissions",
            cost: "£15/unit",
            who_by: "DIY",
            disruption: "Minimal",
            associated_work: "",
            key_risks: "n/a",
            notes: "",
            maintenance: ""
        },
        HW_04: {
            name: "Low-Flow Shower Head",
            source: '',
            description: "Fit new aerating spray head shower head to reduce water flow and hot water demand.",
            performance: '8 litres/minute',
            benefits: "Fuel Bills, Carbon Emissions",
            cost: "£50/unit",
            who_by: "DIY",
            disruption: "Minimal",
            associated_work: "",
            key_risks: "n/a",
            notes: "",
            maintenance: ""
        },
        HW_05: {
            name: "Replace Electric Shower with Direct Feed from Hot Water supply.",
            source: '',
            description: "New direct hot water feed low-flow shower to reduce hot water consumption and energy use (uses mains hot water system rather than own electric heating element).",
            performance: '8 litres/minute',
            benefits: "Fuel Bills, Carbon Emissions",
            cost: "£300/unit",
            who_by: "Plumber/ DIY",
            disruption: "Minimal",
            associated_work: "",
            key_risks: "n/a",
            notes: "",
            maintenance: ""
        }
    },
    storage_type: {
        HWS: {
            tag: 'HWS',
            name: "Test hot water storage",
            manufacturer_loss_factor: 0,
            temperature_factor_a: 0,
            storage_volume: 0,
            loss_factor_b: 0,
            volume_factor_b: 0,
            temperature_factor_b: 0,
            insulation_type: 'very thick',
            declared_loss_factor_known: true,
            source: '',
            description: "",
            performance: '',
            benefits: "",
            cost: "",
            who_by: "",
            disruption: "l",
            associated_work: "",
            key_risks: "",
            notes: "",
            maintenance: ""
        },
    },
    appliances_and_cooking: {
        /*"Clothes washing - hot feed": {
         category: "Laundry",
         "norm_demand": 1.1,
         "units": "kWh per use",
         "utilisation_factor": 1,
         "frequency": 55,
         "reference_quantity": 3,
         "Electric fraction": 0.55,
         "DHW fraction": 0.45,
         "GAS fraction": 0
         },*/
        "LAU1": {
            name: "Clothes washing - cold feed",
            category: "Laundry",
            "norm_demand": 1.1,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 55,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "LAU2": {
            name: "Clothes Drying - electric dryer",
            category: "Laundry",
            "norm_demand": 4,
            "units": "kWh per use",
            "utilisation_factor": 0.88,
            "frequency": 57,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "FST1": {
            name: "Refrigerator",
            category: "Food storage",
            "norm_demand": 0.65,
            "units": "kWh per day",
            "utilisation_factor": 1,
            "frequency": 365,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "FST2": {
            name: "Upright Freezer",
            category: "Food storage",
            "norm_demand": 0.89,
            "units": "kWh per day",
            "utilisation_factor": 1,
            "frequency": 365,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "FST3": {
            name: "Chest Freezer",
            category: "Food storage",
            "norm_demand": 1,
            "units": "kWh per day",
            "utilisation_factor": 1,
            "frequency": 365,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "FST4": {
            name: "Fridge/Freezer",
            category: "Food storage",
            "norm_demand": 1.16,
            "units": "kWh per day",
            "utilisation_factor": 1,
            "frequency": 365,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "COOK1": {
            name: "gas hob, gas oven",
            category: "Cooking",
            "norm_demand": 0.25,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 500,
            "reference_quantity": 3,
            "type_of_fuel": "Gas",
            "efficiency": 1
        },
        "COOK2": {
            name: "gas hob",
            category: "Cooking",
            "norm_demand": 0.25,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 500,
            "reference_quantity": 3,
            "type_of_fuel": "Gas",
            "efficiency": 1
        },
        "COOK3": {
            name: "electric oven",
            category: "Cooking",
            "norm_demand": 0.25,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 500,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "COOK4": {
            name: "electric hob, electric oven (standard)",
            category: "Cooking",
            "norm_demand": 0.22,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 500,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "COOK5": {
            name: "electric hob, electric oven (induction)",
            category: "Cooking",
            "norm_demand": 0.2,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 500,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "COOK6": {
            name: "range/aga - oil",
            category: "Cooking",
            "norm_demand": 425,
            "units": "KWh per week",
            "utilisation_factor": 1,
            "frequency": 52,
            "reference_quantity": 1,
            "type_of_fuel": "Oil",
            "efficiency": 1
        },
        "COOK7": {
            name: "range/aga - gas",
            category: "Cooking",
            "norm_demand": 425,
            "units": "KWh per week",
            "utilisation_factor": 1,
            "frequency": 52,
            "reference_quantity": 1,
            "type_of_fuel": "Gas",
            "efficiency": 1
        },
        "COOK8": {
            name: "range/aga - electric",
            category: "Cooking",
            "norm_demand": 220,
            "units": "KWh per week",
            "utilisation_factor": 1,
            "frequency": 52,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "COOK9": {
            name: "microwave",
            category: "Cooking",
            "norm_demand": 14,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "KTC1": {
            name: "electric kettle",
            category: "Other kitchen / cleaning",
            "norm_demand": 20,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        /*"Dishwasher - hot feed": {
         category: "Other kitchen / cleaning",
         "norm_demand": 1.5,
         "units": "kWh per use",
         "utilisation_factor": 1,
         "frequency": 65,
         "reference_quantity": 3,
         "Electric fraction": 0.5,
         "DHW fraction": 0.5,
         "GAS fraction": 0,
         },*/
        "KTC2": {
            name: "Dishwasher - cold feed",
            category: "Other kitchen / cleaning",
            "norm_demand": 1.5,
            "units": "kWh per use",
            "utilisation_factor": 1,
            "frequency": 65,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "TV1": {
            name: "TV - CRT",
            category: "TV",
            "norm_demand": 118,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "TV2": {
            name: "TV - LCD/LED",
            category: "TV",
            "norm_demand": 199,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "TV3": {
            name: "TV - Plasma",
            category: "TV",
            "norm_demand": 658,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "CMP1": {
            name: "Desktop",
            category: "Computing",
            "norm_demand": 166,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "CMP2": {
            name: "Laptop",
            category: "Computing",
            "norm_demand": 29,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "CMP3": {
            name: "Computer Peripherals",
            category: "Computing",
            "norm_demand": 50,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "MSC1": {
            name: "Small Consumer Electronics",
            category: "Miscelanea",
            "norm_demand": 0.080,
            "units": "kW",
            "utilisation_factor": 1,
            "frequency": 0.55,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "MSC2": {
            name: "Other Small Appliances",
            category: "Miscelanea",
            "norm_demand": 50,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 3,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        },
        "MSC3": {
            name: "Standby",
            category: "Miscelanea",
            "norm_demand": 343,
            "units": "kWh",
            "utilisation_factor": 1,
            "frequency": 1,
            "reference_quantity": 1,
            "type_of_fuel": "Electricity",
            "efficiency": 1
        }
    },
    heating_systems: {
        "CMBB1": {
            name: "Old Gas/LPG Combi Boiler with rads/underfloor heating pipes in timber floor, with storage",
            category: 'Combi boilers',
            winter_efficiency: 70,
            summer_efficiency: 60,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB2": {
            name: "Old Gas/LPG Combi Boiler with radiators, no storage",
            category: 'Combi boilers',
            winter_efficiency: 70,
            summer_efficiency: 60,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB3": {
            name: "Typical Gas/LPG Combi Boiler with radiators, with storage",
            category: 'Combi boilers',
            winter_efficiency: 80,
            summer_efficiency: 70,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB4": {
            name: "Typical Gas/LPG Combi Boiler with radiators, with storage",
            category: 'Combi boilers',
            winter_efficiency: 80,
            summer_efficiency: 70,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB5": {
            name: "New Gas/LPG Combi Boiler with radiators, with storage",
            category: 'Combi boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 120,
            fans_and_supply_pumps: 45,
            responsiveness: 1,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB6": {
            name: "New Gas/LPG Combi Boiler with radiators, no storage",
            category: 'Combi boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 120,
            fans_and_supply_pumps: 45,
            responsiveness: 1,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB7": {
            name: "Old Gas/LPG Combi Boiler with underfloor heating, with storage",
            category: 'Combi boilers',
            winter_efficiency: 70,
            summer_efficiency: 60,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB8": {
            name: "Old Gas/LPG Combi Boiler with underfloor heating, no storage",
            category: 'Combi boilers',
            winter_efficiency: 70,
            summer_efficiency: 60,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB9": {
            name: "Typical Gas/LPG Combi Boiler with underfloor heating, with storage",
            category: 'Combi boilers',
            winter_efficiency: 80,
            summer_efficiency: 70,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB10": {
            name: "Typical Gas/LPG Combi Boiler with underfloor heating no storage",
            category: 'Combi boilers',
            winter_efficiency: 80,
            summer_efficiency: 70,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB11": {
            name: "New Gas/LPG Combi Boiler with underfloor heating, with storage",
            category: 'Combi boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 120,
            fans_and_supply_pumps: 45,
            responsiveness: 0.75,
            combi_loss: 'Storage combi boiler < 55 litres',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB12": {
            name: "New Gas/LPG Combi Boiler with underfloor heating, no storage",
            category: 'Combi boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 120,
            fans_and_supply_pumps: 45,
            responsiveness: 0.75,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB13": {
            name: "Old Oil Combi Boiler with radiators, no keep hot facility",
            category: 'Combi boilers',
            winter_efficiency: 66,
            summer_efficiency: 54,
            central_heating_pump: 156,
            fans_and_supply_pumps: 100,
            responsiveness: 1,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB14": {
            name: "Typical Oil Combi Boiler with radiators, no keep hot facility",
            category: 'Combi boilers',
            winter_efficiency: 80,
            summer_efficiency: 68,
            central_heating_pump: 156,
            fans_and_supply_pumps: 100,
            responsiveness: 1,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "CMBB15": {
            name: "New Oil Combi Boiler with radiators, no keep hot facility",
            category: 'Combi boilers',
            winter_efficiency: 92,
            summer_efficiency: 88,
            central_heating_pump: 120,
            fans_and_supply_pumps: 100,
            responsiveness: 1,
            combi_loss: 'Instantaneous, without keep hot-facility',
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB1": {
            name: "Old Gas/LPG system boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 70,
            summer_efficiency: 60,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB2": {
            name: "Typical Gas/LPG system boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 80,
            summer_efficiency: 70,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB3": {
            name: "New Gas/LPG system boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 120,
            fans_and_supply_pumps: 45,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB4": {
            name: "Old Gas/LPG Combi Boiler with underfloor heating, no keep hot facility",
            category: 'System boilers',
            winter_efficiency: 70,
            summer_efficiency: 60,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB5": {
            name: "Typical Gas/LPG Combi Boiler with underfloor heating no keep hot facility",
            category: 'System boilers',
            winter_efficiency: 80,
            summer_efficiency: 70,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB6": {
            name: "New Gas/LPG Combi Boiler with underfloor heating, no keep hot facility",
            category: 'System boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 126,
            fans_and_supply_pumps: 45,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB7": {
            name: "Old Oil System Boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 66,
            summer_efficiency: 45,
            central_heating_pump: 156,
            fans_and_supply_pumps: 100,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB8": {
            name: "Typical Oil System Boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 80,
            summer_efficiency: 68,
            central_heating_pump: 156,
            fans_and_supply_pumps: 100,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB9": {
            name: "New Oil System Boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 92,
            summer_efficiency: 82,
            central_heating_pump: 120,
            fans_and_supply_pumps: 100,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB10": {
            name: "Old solid fuel boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 65,
            summer_efficiency: 55,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB11": {
            name: "New solid fuel boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 75,
            summer_efficiency: 65,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STMB12": {
            name: "Gasifying Solid Fuel Boiler with rads or underfloor heating pipes in timber floor",
            category: 'System boilers',
            winter_efficiency: 90,
            summer_efficiency: 80,
            central_heating_pump: 120,
            fans_and_supply_pumps: 45,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HPMP1": {
            name: "Electric ground to water heat pump - with rads, flow temp <=35oC",
            category: 'Heat pumps',
            winter_efficiency: 230,
            summer_efficiency: 170,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HPMP2": {
            name: "Electric ground to water heat pump - with underfloor heating, flow temp <=35oC",
            category: 'Heat pumps',
            winter_efficiency: 230,
            summer_efficiency: 170,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HPMP3": {
            name: "Electric ground to water heat pump - with rads, flow temp >35oC",
            category: 'Heat pumps',
            winter_efficiency: 230,
            summer_efficiency: 170,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HPMP4": {
            name: "Electric ground to water heat pump - with underfloor heating, flow temp >35oC",
            category: 'Heat pumps',
            winter_efficiency: 230,
            summer_efficiency: 170,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HPMP5": {
            name: "Electric air to water heat pump - with rads",
            category: 'Heat pumps',
            winter_efficiency: 170,
            summer_efficiency: 170,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HPMP6": {
            name: "Electric air to water heat pump - with underfloor heating",
            category: 'Heat pumps',
            winter_efficiency: 170,
            summer_efficiency: 170,
            central_heating_pump: 156,
            fans_and_supply_pumps: 0,
            responsiveness: 0.75,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT1": {
            name: "Old electric storage heaters",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT2": {
            name: "Typical Electric Storage Heaters",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0.2,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT3": {
            name: "New Electric Storage Heaters",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0.5,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT4": {
            name: "Direct Acting Electric Heaters",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT5": {
            name: "Decorative Fuel Effect gas/LPG fires",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT6": {
            name: "Old Gas/LPG fires",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT7": {
            name: "New Gas/LPG fires",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0.5,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT8": {
            name: "Open fires burning solid fuel",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0.5,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT9": {
            name: "Closed fires burning solid fuel",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0.5,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "ROMHT10": {
            name: "Modern efficient stove burning sold fuel",
            category: 'Room heaters',
            winter_efficiency: 100,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0.5,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "WAS1": {
            name: "Old gas/LPG/oil fired warm air system",
            category: 'Warm air systems',
            winter_efficiency: 70,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 'SFP x 0.4 xVt',
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "WAS2": {
            name: "New gas/LPG/oil fired warm air system",
            category: 'Warm air systems',
            winter_efficiency: 78,
            summer_efficiency: 0,
            central_heating_pump: 0,
            fans_and_supply_pumps: 'SFP x 0.4 xVt',
            responsiveness: 1,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HOTWT1": {
            name: "Electric Immersion System",
            category: 'Hot water only',
            winter_efficiency: 100,
            summer_efficiency: 100,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HOTWT2": {
            name: "Single Point Gas Water Heater (instantaneous at point of use)",
            category: 'Hot water only',
            winter_efficiency: 70,
            summer_efficiency: 70,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HOTWT3": {
            name: "Multi-point gas water heater (instantaneous serving several taps)",
            category: 'Hot water only',
            winter_efficiency: 65,
            summer_efficiency: 65,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "HOTWT4": {
            name: "Range cooker with boiler for heating water only",
            category: 'Hot water only',
            winter_efficiency: 50,
            summer_efficiency: 50,
            central_heating_pump: 0,
            fans_and_supply_pumps: 0,
            responsiveness: 0,
            combi_loss: 0,
            primary_circuit_loss: 'No',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        }
    },
    pipework_insulation: {
        "PWINS1": {
            name: "First 1m from cylinder insulated",
            pipework_insulation: 'First 1m from cylinder insulated',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 1,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "PWINS2": {
            name: "All accesible piperwok insulated",
            pipework_insulation: 'All accesible piperwok insulated',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 2,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "PWINS3": {
            name: "Fully insulated primary pipework",
            pipework_insulation: 'Fully insulated primary pipework',
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 3,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        }
    },
    hot_water_control_type: {
        "STGCTR1": {
            name: "Cylinder thermostat, water heating not separately timed",
            control_type: "Cylinder thermostat, water heating not separately timed",
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 3,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "STGCTR2": {
            name: "Cylinder thermostat, water heating separately timed",
            control_type: "Cylinder thermostat, water heating separately timed",
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 3,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        }
    },
    space_heating_control_type: {
        "SPCTR2": {
            name: "Control type 2",
            control_type: 2,
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 3,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        },
        "SPCTR3": {
            name: "Control type 3",
            control_type: 3,
            source: '---',
            description: "---",
            performance: '---',
            benefits: "---",
            cost: 3,
            who_by: "---",
            disruption: "---",
            associated_work: "---",
            key_risks: "---",
            notes: "---",
            maintenance: "---"
        }
    }

};
